version: '3'
services:
  redis-6379:
    container_name: redis-6379
    image: registry.cn-shenzhen.aliyuncs.com/cocoadel/redis:5.0.4
    restart: always
    ports:
      - "6379:6379"
      - "16379:16379"
    privileged: true
    #配置文件/aof持久化文件/db持久化文件
    volumes: 
      - ./6379/data/:/data/
      - ./6379/logs/:/var/log/redis/
      - ./6379/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.19.0.79
  redis-6380:
    container_name: redis-6380
    image: registry.cn-shenzhen.aliyuncs.com/cocoadel/redis:5.0.4
    restart: always
    ports:
      - "6380:6380"
      - "16380:16380"
    privileged: true
    #配置文件/aof持久化文件/db持久化文件
    volumes: 
      - ./6380/data/:/data/
      - ./6380/logs/:/var/log/redis/
      - ./6380/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.19.0.80

  redis-6381:
    container_name: redis-6381
    image: registry.cn-shenzhen.aliyuncs.com/cocoadel/redis:5.0.4
    restart: always
    ports:
      - "6381:6381"
      - "16381:16381"
    privileged: true
    #配置文件/aof持久化文件/db持久化文件
    volumes: 
      - ./6381/data/:/data/
      - ./6381/logs/:/var/log/redis/
      - ./6381/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.19.0.81

  redis-6382:
    container_name: redis-6382
    image: registry.cn-shenzhen.aliyuncs.com/cocoadel/redis:5.0.4
    restart: always
    ports:
      - "6382:6382"
      - "16382:16382"
    privileged: true
    #配置文件/aof持久化文件/db持久化文件
    volumes: 
      - ./6382/data/:/data/
      - ./6382/logs/:/var/log/redis/
      - ./6382/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.19.0.82

  redis-6383:
    container_name: redis-6383
    image: registry.cn-shenzhen.aliyuncs.com/cocoadel/redis:5.0.4
    restart: always
    ports:
      - "6383:6383"
      - "16383:16383"
    privileged: true
    #配置文件/aof持久化文件/db持久化文件
    volumes: 
      - ./6383/data/:/data/
      - ./6383/logs/:/var/log/redis/
      - ./6383/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.19.0.83

  redis-6384:
    container_name: redis-6384
    image: registry.cn-shenzhen.aliyuncs.com/cocoadel/redis:5.0.4
    restart: always
    ports:
      - "6384:6384"
      - "16384:16384"
    privileged: true
    #配置文件/aof持久化文件/db持久化文件
    volumes: 
      - ./6384/data/:/data/
      - ./6384/logs/:/var/log/redis/
      - ./6384/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.19.0.84

networks:
   redis-net:
      ipam:
         config:
         - subnet: 172.19.0.0/16



