package pers.cocoadel.homework.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;
import pers.cocoadel.homework.mybatis.domain.CoffeeEntry;
import pers.cocoadel.homework.mybatis.domain.CoffeeEntryExample;

public interface CoffeeEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    long countByExample(CoffeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    int deleteByExample(CoffeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    @Delete({
        "delete from t_coffee",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    @Insert({
        "insert into t_coffee (name, price, ",
        "create_time, update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT,typeHandler=pers.cocoadel.homework.mybatis.handler.MoneyTypeHandler}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    int insert(CoffeeEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    int insertSelective(CoffeeEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    List<CoffeeEntry> selectByExampleWithRowbounds(CoffeeEntryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    List<CoffeeEntry> selectByExample(CoffeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    @Select({
        "select",
        "id, name, price, create_time, update_time",
        "from t_coffee",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("pers.cocoadel.homework.mybatis.mapper.CoffeeEntryMapper.BaseResultMap")
    CoffeeEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") CoffeeEntry record, @Param("example") CoffeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    int updateByExample(@Param("record") CoffeeEntry record, @Param("example") CoffeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    int updateByPrimaryKeySelective(CoffeeEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffee
     *
     * @mbg.generated Thu Nov 19 08:52:59 CST 2020
     */
    @Update({
        "update t_coffee",
        "set name = #{name,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=BIGINT,typeHandler=pers.cocoadel.homework.mybatis.handler.MoneyTypeHandler},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CoffeeEntry record);
}